name: Build and publish Docker image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
        env:
          SQLITE_DB_LOCATION: /tmp/todo.db

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{Hidenori333}}
          password: ${{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}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{https://github.com/Hidenori333/todo.git}}:latest
            ghcr.io/${{https://github.com/Hidenori333/todo.git}}:1.0.0